name: AML Mod Compiler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository...
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Android NDK (r27c)...
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r27c
        local-cache: true

    - name: Build ARMPatch...
      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./ARMPatch/armpatch_src/Android.mk NDK_APPLICATION_MK=./ARMPatch/armpatch_src/Application.mk NDK_DEBUG=0 -j12
      
    - name: Build AML...
      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk NDK_DEBUG=0 -j12

    - name: Upload the mod!
      uses: actions/upload-artifact@v3
      with:
        name: AML_Libraries
        path: ./libs/**/libAML.so
